##
## EPITECH PROJECT, 2025
## B-PDG-300-MAR-3-1
## File description:
## Makefile
##

NAME	=	z

SRC		=	z.c \

FLAGS  =   -std=gnu17 -Wall -Wextra

all:
	gcc -o $(NAME) $(SRC) $(FLAGS)

clean:
	rm -f *.o

fclean:	clean
	rm -f $(NAME)

re:	fclean all
