##
## EPITECH PROJECT, 2025
## B-PDG-300-MAR-3-1
## File description:
## Makefile
##

NAME	=	doop

SRC		=	task13.hs

all:
	ghc -o $(NAME) $(SRC)

clean:
	rm -f *.o *.hi

fclean:	clean
	rm -f $(NAME)

re:	fclean all
