##
## EPITECH PROJECT, 2025
## B-PDG-300-MAR-3-1
## File description:
## Makefile
##

NAME	=	StupidUnitConverter

FLAGS   =   -std=c++20 -Wall -Wextra -Werror

all:
	g++ -o $(NAME) *.cpp $(FLAGS)
	rm -f *.o

clean:
	rm -f *.o

fclean:	clean
	rm -f $(NAME)

re:	fclean all
